### ISSUE TITLE
quiz answer 校验答案的style有问题

### ISSUE THREAD

**Issue by lemonzeng** [zlnortheastern/kanbas-quizzes-group9#12]
1. quiz answer 校验答案的style有问题
不知道为啥，我昨天看都还是好好的。
![image](https://github.com/user-attachments/assets/da103283-d474-4fb6-9f4f-5bc6c5a9ce43)
2. 计算answer的得分有误：
 1）question3 没答对应该是0pts；
![image](https://github.com/user-attachments/assets/ba2070d7-8840-4cac-8351-581de7642b33)
 2）计算总分有误： total score 应该是9， 不是13.
![image](https://github.com/user-attachments/assets/ab2678d3-2259-45b7-b9d3-3bc500311b62)

**Comment by zlnortheastern** [comment]
[https://github.com/zlnortheastern/kanbas-quizzes-server/pull/8](url)
