### ISSUE TITLE
quiz中的points 和 answer中的 total 应该是一致的，但现在不一样。

### ISSUE THREAD

**Issue by lemonzeng** [zlnortheastern/kanbas-quizzes-group9#14]
i.e.
![image](https://github.com/user-attachments/assets/e821c8ae-5196-436d-9a5f-ff0350a1b95f)
![image](https://github.com/user-attachments/assets/fb1a075b-e041-45ba-9b43-7696a798100c)

**Comment by zlnortheastern** [comment]
[https://github.com/zlnortheastern/kanbas-quizzes-group9/pull/26](url)
