### ISSUE TITLE
T or F 比对逻辑待核对

### ISSUE THREAD

**Issue by lemonzeng** [zlnortheastern/kanbas-quizzes-group9#24]
<img width="1273" alt="1723386863847" src="https://github.com/user-attachments/assets/340f4e2a-213d-49a1-8fb1-cb421647a202">
![image](https://github.com/user-attachments/assets/15311f14-2933-4578-9cc9-275a99161f25)

**Comment by zlnortheastern** [comment]
@lemonzeng 更新后强制答完题目才能submit这样下面这个更改改回去判断对错的逻辑就正常了
![image](https://github.com/user-attachments/assets/a07a4599-d0df-4d3a-9c48-342fc6f192ef)
