### ISSUE TITLE
score 计算的问题

### ISSUE THREAD

**Issue by lemonzeng** [zlnortheastern/kanbas-quizzes-group9#27]
![image](https://github.com/user-attachments/assets/a4f3830e-ce91-44b7-b3e0-8f787d0d1c40)
total score 正确；
但是在每道题的判断上，有问题；具体是，answer为 非正确答案, 但是被判为正确；

**Comment by zlnortheastern** [comment]
[https://github.com/zlnortheastern/kanbas-quizzes-group9/pull/26/commits/e3fa906dc57b1f86983fc11e1dae648169fd670b](url) 已修复
