### ISSUE TITLE
multiple attempts的how many attempts 默认值是1，目前是-1

### ISSUE THREAD

**Issue by shufanfan** [zlnortheastern/kanbas-quizzes-group9#28]
<img width="510" alt="Screenshot 2024-08-13 at 13 29 01" src="https://github.com/user-attachments/assets/a217d8dc-b05c-4e6b-96e7-944c20f50c6f">

**Comment by zlnortheastern** [comment]
<img width="786" alt="截屏2024-08-14 09 50 28" src="https://github.com/user-attachments/assets/088c6337-24f1-4239-adf0-24149cc847ee">

看成-1了 已修复[https://github.com/zlnortheastern/kanbas-quizzes-group9/pull/26](url)
