### ISSUE TITLE
创建完一个新的quiz后，点击quiz details页面的preview按钮，会报错

### ISSUE THREAD

**Issue by shufanfan** [zlnortheastern/kanbas-quizzes-group9#29]
<img width="593" alt="Screenshot 2024-08-13 at 13 35 10" src="https://github.com/user-attachments/assets/aa1b6fdd-51d7-4642-b8c1-c9cf0faa30aa">
<img width="511" alt="Screenshot 2024-08-13 at 13 35 36" src="https://github.com/user-attachments/assets/2f00de53-8024-4e7e-a9ed-7b07789990c8">

**Comment by zlnortheastern** [comment]
已更新[https://github.com/zlnortheastern/kanbas-quizzes-group9/pull/26](url)
