### ISSUE TITLE
有一些quiz里没有questions，但是quiz有分数

### ISSUE THREAD

**Issue by shufanfan** [zlnortheastern/kanbas-quizzes-group9#30]
<img width="933" alt="Screenshot 2024-08-13 at 13 39 31" src="https://github.com/user-attachments/assets/ef891e1d-b8de-4e3b-8c06-8843e55a2064">

**Comment by zlnortheastern** [comment]
那是因为数据库数据是这样的 我们只有在创建或者edit的时候才会把quiz分数跟questions连接起来 需要手动改数据库的分数或者把这些quiz删掉
