### ISSUE TITLE
Quiz questions editor screen的cancel按钮

### ISSUE THREAD

**Issue by shufanfan** [zlnortheastern/kanbas-quizzes-group9#31]
![image](https://github.com/user-attachments/assets/7c0c1900-f593-4447-a0f1-2a0255c34b58)
<img width="468" alt="image" src="https://github.com/user-attachments/assets/966cd53f-76fa-480c-8418-f9217e4d7cb5">

**Comment by zlnortheastern** [comment]
上面这个是问题还是要求，目前edit已存在的问题点cancel不会让问题变空

https://github.com/user-attachments/assets/adec3253-bc07-46dc-ade5-a54a09d3ed01

**Comment by shufanfan** [comment]
现在还有一个问题是，添加一个新的问题，如果在编辑这个新问题的过程中不想要这个问题了，点击cancel会产生一个空问题，只能再点delete按钮才能把问题删除。

**Comment by zlnortheastern** [comment]
> 现在还有一个问题是，添加一个新的问题，如果在编辑这个新问题的过程中不想要这个问题了，点击cancel会产生一个空问题，只能再点delete按钮才能把问题删除。

对啊 这不就是正常逻辑吗 点add question就会产生新问题 不想要就点delete删掉 至于是不是空问题 那也是用户自定义的 本来就允许空问题

**Comment by shufanfan** [comment]
你说的有道理，就按你说的来。我刚才意思是，在一个问题被创建保存之前如果不想要这个问题，难道不是点击cancel之后就不出现这个问题吗？就好比我想发一条微博，但是我在编辑的过程中不想发这条微博了，我点击cancel，也并不会出现一条空微博。

**Comment by zlnortheastern** [comment]
> 你说的有道理，就按你说的来。我刚才意思是，在一个问题被创建保存之前如果不想要这个问题，难道不是点击cancel之后就不出现这个问题吗？就好比我想发一条微博，但是我在编辑的过程中不想发这条微博了，我点击cancel，也并不会出现一条空微博。

我知道 但是目前这样没有逻辑上的问题就不需要改了 我们这个逻辑跟微博之类的不一样 我们这个是问题集编辑页面 需要整个问题编辑完点击最下面那个save才会发布更改 而微博那种是每条都会发布 这两个逻辑不一样 当然也可以按你说的那么改 但是改起来很麻烦每个cnacel按钮还要加判断条件判断是不是新建的问题 我们要从代码来思考怎么实现的
