### ISSUE TITLE
想了下，感觉attempt次数的设置 如果是no的话应该是默认1次而不是无数次，这样逻辑比较合理，可讨论，不重要

### ISSUE THREAD

**Issue by lemonzeng** [zlnortheastern/kanbas-quizzes-group9#39]
![image](https://github.com/user-attachments/assets/90478f07-cb1a-473d-9735-0d156700ccfa)
![image](https://github.com/user-attachments/assets/0b58bbc1-4fad-42b0-9f70-40239fd49607)
![image](https://github.com/user-attachments/assets/ca5cfb44-892c-49f7-b22f-174cb5058df2)

**Comment by zlnortheastern** [comment]
这个是因为在以往我们使用Canvas的经验来看 存在可尝试数无数次的quiz 我感觉multipleAttempt这个属性就是为了判断是否是无限次尝试 要不我们完全可以只用一个attempt limit的属性 那这样的话multipleAttempt这个boolean就失去意义了
